# Generated by Django 2.0.7 on 2022-04-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_Main_Img',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
    ]
